# .github/workflows/release.yml

name: Release

on:
  push:
    tags:
      - "v*.*.*" # e.g. v0.1.0
  workflow_dispatch: {}

permissions:
  contents: write # Required to create/update GitHub Releases

jobs:
  build-and-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            args: ""
          - platform: ubuntu-22.04
            args: ""
          - platform: windows-latest
            args: ""

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Use the built-in caching for npm

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libssl-dev \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev

      - name: Install npm dependencies
        run: npm ci # 'ci' is faster and safer for CI environments

      - name: Build app and create Release
        id: tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # The tagName is set to the version from tauri.conf.json
          tagName: v__VERSION__
          releaseName: "Matrix Protocol Helper v__VERSION__"
          releaseBody: "See the assets below for platform-specific installers and checksums."
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}

      - name: Generate and upload checksums
        if: steps.tauri.outputs.artifactPaths != ''
        shell: bash
        run: |
          set -euo pipefail
          # Create a checksums file for all artifacts produced on this runner
          cd src-tauri/target/release/bundle
          
          # Use shasum for macOS/Linux and sha256sum for Windows (via Git Bash)
          if command -v sha256sum >/dev/null 2>&1; then
            sha256sum ./**/*.* > SHA256SUMS.txt
          else
            shasum -a 256 ./**/*.* > SHA256SUMS.txt
          fi
          
          # Upload the checksums file to the release
          gh release upload \
            v${{ steps.tauri.outputs.appVersion }} \
            SHA256SUMS.txt \
            --clobber # Overwrite if it already exists from another job
        env:
          # The GitHub CLI is pre-installed on runners and authenticated via GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}