name: Release

on:
  push:
    tags:
      - "v*.*.*"   # e.g. v0.1.0
  workflow_dispatch: {}

permissions:
  contents: write  # create/update releases

jobs:
  build-and-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            args: ""
          - platform: ubuntu-22.04
            args: ""
          - platform: windows-latest
            args: ""

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            build-essential
          # Try 4.1 if available (harmless if not found)
          sudo apt-get install -y libwebkit2gtk-4.1-dev || true

      - name: Install JS dependencies (npm)
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build app and upload to Release
        id: tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # If triggered by a tag, use it; otherwise let the action infer from tauri.conf.json
          tagName: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || '' }}
          releaseName: ${{ startsWith(github.ref, 'refs/tags/') && format('Matrix Protocol Helper {0}', github.ref_name) || 'Matrix Protocol Helper v__VERSION__' }}
          releaseBody: "See the assets below for platform-specific installers and checksums."
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}

      - name: Generate checksums
        if: ${{ steps.tauri.outputs.artifactPaths != '' }}
        shell: bash
        run: |
          set -euo pipefail
          ART_LIST='${{ steps.tauri.outputs.artifactPaths }}'
          # Normalize artifact paths (JSON array or space-separated) to one-per-line using Node (no heredocs)
          node -e "const v=(process.env.ART_LIST||'').trim(); let arr; try{arr=JSON.parse(v);}catch{arr=v.split(/\s+/);} for(const p of arr){ if(p) console.log(p); }" > artifacts.txt
          rm -f SHA256SUMS.txt
          while IFS= read -r f; do
            [ -f "$f" ] || continue
            if command -v sha256sum >/dev/null 2>&1; then
              sha256sum \"$f\" >> SHA256SUMS.txt
            else
              shasum -a 256 \"$f\" >> SHA256SUMS.txt
            fi
          done < artifacts.txt

      - name: Upload checksums to Release
        if: ${{ steps.tauri.outputs.appVersion != '' && hashFiles('SHA256SUMS.txt') != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.tauri.outputs.appVersion }}
          files: SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
